#!/usr/bin/env bash

read -r -d '' cmd <<- EOM
    /home/ji/conf/gams/gamsdir/gams34.3_linux_x64_64_sfx/model2tex.sh $@
EOM

sudo iptables -I OUTPUT 1 -m owner --gid-owner no-net -j DROP 
sg no-net "$cmd"
