#!/usr/bin/env python3

from pandocfilters import toJSONFilter, DefinitionList, RawInline, Para

def remove_period_lines(key, value, format, meta):
  if format != 'latex':
    return
  if key == 'DefinitionList':
    change = False
    for deflist in value:
      d = deflist[1][0][0]['c'][0]
      if d['c'] == ".":
        change = True
        d['t'] = "RawInline"
        d['c'] = ["latex", "\\null\\hfill"]
    if change:
      return DefinitionList(value)

if __name__ == "__main__":
  toJSONFilter(remove_period_lines)
