#!/usr/bin/env zsh

# very useful reference

#setxkbmap -option "lv3:alt_switch,shift:both_capslock"
#setxkbmap -option "lv3:alt_switch"
setxkbmap -option "shift:both_capslock"

# xmodmap -pke  shows all key codes

# keycode  29 = z Z y Y leftarrow yen
# keycode  38 = a A a A ae AE
# keycode  39 = s S s S U017F U1E9E
# keycode  40 = d D d D eth ETH
# keycode  41 = f F f F dstroke ordfeminine
# keycode  42 = g G g G eng ENG
# keycode  52 = y Y z Z guillemotright U203A
# keycode  53 = x X x X guillemotleft U2039
# keycode  54 = c C c C cent copyright
# keycode  55 = v V v V doublelowquotemark singlelowquotemark
# keycode  57 = n N n N rightdoublequotemark rightsinglequotemark


echo "started running"
xmodmap -e 'keycode  19 = 0 equal 0 parenright braceright U2260'
xmodmap -e 'keycode  38 = a A a A braceleft leftarrow'
xmodmap -e 'keycode  39 = s S s S bracketleft downarrow'
xmodmap -e 'keycode  40 = d D d D bracketright rightarrow'
xmodmap -e 'keycode  25 = w W w W percent uparrow'
xmodmap -e 'keycode  27 = r R r R asciicircum registered'
xmodmap -e 'keycode  41 = f F f F braceright ordfeminine'
xmodmap -e 'keycode  42 = g G g G backslash U21D4' # U21D4 = ⇔
xmodmap -e 'keycode  52 = y Y z Z ampersand U203A'
xmodmap -e 'keycode  53 = x X x X dollar U2039'
xmodmap -e 'keycode  54 = c C c C parenleft copyright'
xmodmap -e 'keycode  55 = v V v V parenright singlelowquotemark'
xmodmap -e 'keycode  57 = n N 0 N Uf1 Ud1'
xmodmap -e 'keycode  47 = odiaeresis Odiaeresis semicolon colon Home doubleacute'
xmodmap -e 'keycode  48 = adiaeresis Adiaeresis apostrophe quotedbl End asciicircum'
xmodmap -e 'keycode  30 = u U 7 U U2606 uparrow'
xmodmap -e 'keycode  31 = i I 8 I U2605 idotless'
xmodmap -e 'keycode  32 = o O 9 O division Oslash'

xmodmap -e 'keycode  28 = t T t T U25CD Tslash' # U25CD = ◍
xmodmap -e 'keycode  29 = z Z y Y U25A4 yen' # U25A4 = ▤

xmodmap -e 'keycode 43 = h H h H Left U21D0 Left Left h H'
xmodmap -e 'keycode 44 = j J 4 J Down U21D3 Down Down j J'
xmodmap -e 'keycode 45 = k K 5 K Up U21D1 Up Up k K'
xmodmap -e 'keycode 46 = l L 6 L Right U21D2 Right Right l L'

xmodmap -e 'keycode 59 = comma semicolon 2 less less multiply'
#xmodmap -e 'keycode 59 = 1 2 3 4 5 6 7 8 9'
xmodmap -e 'keycode 60 = period colon 3 greater greater division'
xmodmap -e 'keycode  61 = minus underscore slash question bar dead_macron'

xmodmap -e 'keycode  63 = KP_Multiply comma KP_Multiply comma KP_Multiply comma XF86Prev_VMode KP_Multiply KP_Multiply XF86Prev_VMode KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86Prev_VMode KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86Prev_VMode'
xmodmap -e 'keycode  82 = KP_Subtract plusminus KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode KP_Subtract KP_Subtract XF86Prev_VMode KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode'
xmodmap -e 'keycode  86 = KP_Add Tab KP_Add Tab KP_Add Tab XF86Next_VMode KP_Add KP_Add XF86Next_VMode KP_Add KP_Add KP_Add KP_Add XF86Next_VMode KP_Add KP_Add KP_Add KP_Add XF86Next_VMode'
xmodmap -e 'keycode  91 = period KP_Delete period KP_Delete period KP_Delete period KP_Delete'
xmodmap -e 'keycode 106 = KP_Divide semicolon KP_Divide semicolon KP_Divide semicolon XF86Ungrab KP_Divide KP_Divide XF86Ungrab KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab'

#xmodmap -e 'keycode 65 = ISO_Level3_Shift nobreakspace space nobreakspace space nobreakspace space nobreakspace'
xmodmap -e 'keycode 65 = ISO_Level3_Shift nobreakspace space nobreakspace space nobreakspace space nobreakspace'
xmodmap -e 'keycode 253 = space'

echo "adjusting mode spwitches"

# dead key setup
# cat .XCompose | grep -o -E "<dead_[^>]+>" | sort -u
# this shows all available dead keys
xmodmap -e 'keycode  58 = m M 1 M dead_greek masculine'
xmodmap -e 'keycode  26 = e E e E dead_currency dead_currency'

# This quit working when I enabeled Cabs_Lock as Control_L (and Escape)
# # xmodmap -pm gives inforamtion about available modifier keys
# xmodmap -e 'clear mod3'
# xmodmap -e 'clear mod5'
#
# #xmodmap -e 'keycode  49 = Mode_switch degree grave asciitilde dead_caron dead_caron'
# xmodmap -e 'keycode  49 = Mode_switch'
# #echo "Setting up Mode_switch as mod3 and mod5"
# xmodmap -e 'add mod3 = Mode_switch'
# xmodmap -e 'add mod5 = ISO_Level3_Shift'
# #echo "Done setting up mod3 and mod5"

#xmodmap -e 'keycode  49 = asciicircum degree grave asciitilde dead_caron dead_caron'


# todo setup box-drawing chars as 3rd numpad level
# https://en.wikipedia.org/wiki/Box-drawing_character

# keycode  77 = Num_Lock NoSymbol Num_Lock NoSymbol Num_Lock Num_Lock
# keycode  78 = Scroll_Lock NoSymbol Scroll_Lock NoSymbol Scroll_Lock Scroll_Lock
# keycode  79 = KP_Home KP_7 KP_Home KP_7 KP_Home KP_7 KP_Home KP_7
#
# xmodmap -e 'keycode  79 = A B C D E F G H'
#
# keycode  80 = KP_Up KP_8 KP_Up KP_8 KP_Up KP_8 KP_Up KP_8
# keycode  81 = KP_Prior KP_9 KP_Prior KP_9 KP_Prior KP_9 KP_Prior KP_9
# keycode  82 = KP_Subtract plusminus KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode KP_Subtract KP_Subtract XF86Prev_VMode KP_Subtract
# keycode  83 = KP_Left KP_4 KP_Left KP_4 KP_Left KP_4 KP_Left KP_4
# keycode  84 = KP_Begin KP_5 KP_Begin KP_5 KP_Begin KP_5 KP_Begin KP_5
# keycode  85 = KP_Right KP_6 KP_Right KP_6 KP_Right KP_6 KP_Right KP_6
# keycode  86 = KP_Add Tab KP_Add Tab KP_Add Tab XF86Next_VMode KP_Add KP_Add XF86Next_VMode KP_Add
# keycode  87 = KP_End KP_1 KP_End KP_1 KP_End KP_1 KP_End KP_1
# keycode  88 = KP_Down KP_2 KP_Down KP_2 KP_Down KP_2 KP_Down KP_2
# keycode  89 = KP_Next KP_3 KP_Next KP_3 KP_Next KP_3 KP_Next KP_3
# keycode  90 = KP_Insert KP_0 KP_Insert KP_0 KP_Insert KP_0 KP_Insert KP_0
# keycode  91 = period KP_Delete period KP_Delete period KP_Delete period KP_Delete
# keycode  92 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift NoSymbol ISO_Level3_Shift ISO_Level3_Shift
# keycode 104 = KP_Enter NoSymbol KP_Enter NoSymbol KP_Enter KP_Enter
# keycode 106 = KP_Divide semicolon KP_Divide semicolon KP_Divide semicolon XF86Ungrab KP_Divide KP_Divide XF86Ungrab KP_Divide
# keycode 125 = KP_Equal NoSymbol KP_Equal NoSymbol KP_Equal KP_Equal

# keycode  37 = Control_L NoSymbol Control_L NoSymbol Control_L Control_L
# keycode 104 = KP_Enter NoSymbol KP_Enter NoSymbol KP_Enter KP_Enter

echo "Reached handeling of Caps_Lock and return keys"

#xmodmap -e 'keycode   9 = Caps_Lock NoSymbol Caps_Lock NoSymbol Caps_Lock Caps_Lock'
xmodmap -e 'keycode   9 = Super_R NoSymbol Super_R NoSymbol Super_R Super_R'
xmodmap -e 'keycode  66 = Control_R NoSymbol Control_L NoSymbol Control_L Control_L'
xmodmap -e 'keycode 247 = Escape'
#xmodmap -e 'keycode  66 = Escape NoSymbol Escape NoSymbol Escape Escape'
xmodmap -e 'keycode 105 = Multi_key Multi_key Multi_key Multi_key Multi_key Multi_key Multi_key Multi_key'
#xmodmap -e 'keycode  36 = Control_R NoSymbol Control_R NoSymbol Control_R Control_R'
#xmodmap -e 'keycode 248 = Return'
xmodmap -e 'keycode  36 = Return NoSymbol Return NoSymbol Return Return'

xmodmap -e 'keycode  64 = Alt_L Meta_L Alt_L Meta_L Alt_L Meta_L Alt_L Meta_L'

echo "enabeling tabbdance through xcape"

# Clear previous xcape stuff
pidof xcape | xargs kill -1
#xcape -e 'Shift_L=parenleft;Shift_R=parenright;ISO_Level3_Shift=space' -t 0
#xcape -e 'ISO_Level3_Shift=space;Mode_switch=asciicircum' -t 0
#xcape -e 'ISO_Level3_Shift=space' -t 0
xcape -e 'ISO_Level3_Shift=space;Control_R=Escape' -t 300 
# setup numpad as mouse
# xkbset ma 60 10 10 5 2

